# Generated by Django 3.2 on 2022-03-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user_id',)},
        ),
    ]
